export const carBodyTypes: string[] = [
    "Convertible",
    "Coupe",
    "Hatchback",
    "Minivan",
    "Pickup Truck",
    "Sedan",
    "Sports Car",
    "Station Wagon",
    "SUV",
    "Truck",
    "Van",
    "Roadster",
    "Crossover",
    "Microcar",
    "Compact",
    "Luxury",
    "Electric",
    "Hybrid",
    "Limousine"
];
