export const carColors: string[] = [
    "Alpine White",
    "Antique Bronze",
    "Arctic Silver",
    "Aurora Black",
    "Baltic Blue",
    "Beige",
    "Black",
    "Blue",
    "Bright Red",
    "Brown",
    "Burgundy",
    "Candy Apple Red",
    "Champagne",
    "Charcoal",
    "Cobalt Blue",
    "Copper",
    "Cream",
    "Crimson",
    "Dark Blue",
    "Dark Green",
    "Deep Purple",
    "Emerald Green",
    "Forest Green",
    "Gold",
    "Gray",
    "Green",
    "Ivory",
    "Jet Black",
    "Lavender",
    "Light Blue",
    "Light Green",
    "Lime Green",
    "Maroon",
    "Matte Black",
    "Midnight Blue",
    "Navy Blue",
    "Olive",
    "Orange",
    "Pearl White",
    "Pink",
    "Purple",
    "Red",
    "Rose Gold",
    "Royal Blue",
    "Ruby Red",
    "Sandstone",
    "Silver",
    "Slate Gray",
    "Sunset Orange",
    "Tan",
    "Teal",
    "Turquoise",
    "Violet",
    "White",
    "Yellow"
];
